export const Theme = {
    fundo: '#F4F5FC',
    menuFundo: '#E2EBFC',
    calendarioFundo: '#FDFCFF',
    calendarioHeaderFundo: '#FDFCFF',
    border: '#EEEFF6',
    borderPerfil: 'white',
    textoPrimary: '#454D56',
    textoSecondary: '#9EA9BA',
    textoSecondaryVariant: '#8F959E',
    textoAccent: '#418EE2',
    horaSeletor: '#E8E9F2',
    hoverFundo: 'rgba( 255, 255, 255, 0.35 )',
    aula: '#3DEB65',
    reuniao: '#2A8CF1',
    curso: '#FFA426',
    outro: '#FC90F2',
};